# Generated by Django 5.1.1 on 2024-10-20 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_rename_available_dates_workshop_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='workshop',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='max_students',
        ),
        migrations.AddField(
            model_name='workshop',
            name='available_slots',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='location',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='WorkshopBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=200, null=True)),
                ('organization_type', models.CharField(choices=[('school', 'School'), ('company', 'Company'), ('private', 'Private Individual')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('number_of_attendees', models.PositiveIntegerField()),
                ('additional_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.workshop')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
