# Generated by Django 5.1.1 on 2024-11-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_booking_user_remove_booking_workshop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='available_slots',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='location',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='time',
        ),
    ]
