# Generated by Django 5.1.1 on 2024-11-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_booking_user_remove_booking_workshop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available_slots', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
