# Generated by Django 5.1.1 on 2024-11-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_workshop_available_slots_remove_workshop_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopbooking',
            name='user',
        ),
        migrations.AddField(
            model_name='workshopbooking',
            name='contact_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
