# Generated by Django 5.1.1 on 2024-12-02 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bookingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdate',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_dates', to='api.workshop'),
        ),
    ]
