# Generated by Django 5.1.1 on 2024-12-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bookingdate_workshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopbooking',
            name='additional_message',
        ),
        migrations.RemoveField(
            model_name='workshopbooking',
            name='number_of_attendees',
        ),
        migrations.AddField(
            model_name='workshopbooking',
            name='first_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AddField(
            model_name='workshopbooking',
            name='hear_about_us',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('social_media', 'Social Media'), ('word_of_mouth', 'Word of Mouth'), ('advertisement', 'Advertisement')], default='other', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workshopbooking',
            name='last_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workshopbooking',
            name='message',
            field=models.TextField(default='No message provided'),
        ),
        migrations.AddField(
            model_name='workshopbooking',
            name='postcode',
            field=models.CharField(blank=True, default='00000', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workshopbooking',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workshopbooking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='workshopbooking',
            name='organization_name',
            field=models.CharField(blank=True, default='Not Provided', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workshopbooking',
            name='organization_type',
            field=models.CharField(choices=[('school', 'School'), ('company', 'Company'), ('private', 'Private Individual')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='workshopbooking',
            name='phone_number',
            field=models.CharField(blank=True, default='0000000000', max_length=15, null=True),
        ),
    ]
