# Generated by Django 5.1.2 on 2025-01-06 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_workshopbooking_additional_message_and_more'),
        ('api', '0007_workshop_image_workshopbooking_workshop_date'),
    ]

    operations = [
    ]
