# Generated by Django 5.1.2 on 2025-01-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20250106_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopbooking',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='workshopbooking',
            name='hear_about_us',
        ),
        migrations.RemoveField(
            model_name='workshopbooking',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='workshopbooking',
            name='message',
        ),
        migrations.RemoveField(
            model_name='workshopbooking',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='workshopbooking',
            name='title',
        ),
        migrations.AddField(
            model_name='workshopbooking',
            name='additional_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshopbooking',
            name='number_of_attendees',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshopbooking',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshopbooking',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workshopbooking',
            name='organization_type',
            field=models.CharField(choices=[('school', 'School'), ('company', 'Company'), ('private', 'Private Individual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workshopbooking',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookingDate',
        ),
    ]
